Update collectionRunner.yml

diff --git a/.github/workflows/collectionRunner.yml b/.github/workflows/collectionRunner.yml
--- a/.github/workflows/collectionRunner.yml
+++ b/.github/workflows/collectionRunner.yml
@@ -31,6 +31,14 @@ jobs:
       - name: Export Summary from Outputs
         run: |
           echo ${{ steps.run-api-tests.outputs.summary }}
+          
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit 
 
 
     
